export const defaultFile = `As “the guardian of the genome”, p53 has received significant attention for monitoring genome integrity and regulating DNA repair. More than half of human cancers have been shown to express at least a mutant version of p53. Reconstitution of a functional p53 network is an attractive anti-cancer strategy, but therapeutic strategies to restore function have been limited to p53 and its nearest neighbors. Strategies have focused on changing the function of mutant p53, through proteasome- or autophagy-mediated degradation of mutant p53, conversion of mutant p53 to wild-type p53, inhibiting either MDM2 transcription or MDM2-mediated degradation of p53, and to a much lesser extent, interference in the signaling pathways downstream of p53. Considering the centrality of p53 and its prevalence in cancer, the availability of therapeutic approaches is disappointing. A class of post-transcriptional regulators, termed microRNAs (miRNAs), is directly associated with p53, either by regulating or being regulated by p53 and its partners. This network plays a crucial role in fine-tuning the p53 response and maintaining homeostasis in normal cellular processes and stress conditions (1–5).

We are specifically interested in miR-34a networks. miR-34a loss, driven by mutant p53, has been observed in a wide range of solid and hematological malignancies, including cancers of the lung, prostate, breast, pancreas, colon, kidney, bladder, skin, and brain (3,5–11). Replacement therapy based on delivery of miR-34a has been shown to have anti-oncogenic activity: Antagonizing cancer cell viability, stemness, metastasis and drug resistance, miR-34a showed broad applicability, robust therapeutic efficacy, and significant synergy in both in vitro studies and in preclinical evaluations (5,7,8,12–17). While many studies have sought to explain the action of miR-34a, the specific targets of miR-34a that mediate its anti-oncogenic function and the degree to which those targets collaborate or antagonize to achieve the observed phenotypes remain largely unknown. Here we aim to unravel the impact of these connections.

A “perturbed” network, such as one with p53 mutations, or in our case mutations in miR-34-related programs, disrupts the normal homeostatic control mechanisms. This can lead to abnormal cellular responses, loss of regulation, and increased sensitivity to external cues, impacting the overall stability and functionality of the network. We believe that understanding these miR-34a targeted networks/programs will open the path to future approaches that adjust homeostasis therapeutically (e.g., gene therapy, small molecules, network rewiring, combinatorial therapies) or exploit them through synthetic lethality. Arguably of more immediate significance will be developing strategies for personalized medicine. Analyzing the specific characteristics of an individual's genomic information, such as the type of mutation and associated network alterations, can guide the selection of targeted therapies tailored to the patient's unique genetic profile.

Combining experimental and computational approaches, our team is well-positioned to perform the proposed aims. Specifically, we combine expertise in genome editing/systems biology (Bleris), microRNA/cancer biology (Pertsemlidis). Our team has a history of studying theoretical and experimental aspects of miRNA networks (18–20) and miRNA cancer biology/therapeutics (21,22). We also have extensive experience combining theory and experiments towards bottom-up characterization of networks (Molecular Systems Biology (23,24)) and top-down reverse engineering approaches (PNAS and ACS Synthetic Biology (25,26)). We believe that the integration of genome editing technologies and systems biology can redefine our understanding of mutant p53 homeostasis and will shed new light on the functional roles of miR-34a in tumor suppression and cancer development.

We propose to dissect miR-34a interaction networks using state-of-the-art genome editing, single-cell sequencing and thorough characterization methodologies. By studying the functional consequences of genetic modifications, we will gain insights into how these alterations affect cellular homeostasis. We will identify the specific interactions in which miR-34a participates that mediate its anti-oncogenic function and the degree to which the weights of those interactions collaborate or antagonize to achieve the observed phenotypes.

More specifically, we aim to harness the therapeutic benefits of miR-34a replacement therapy, particularly focusing on identifying critical mediators of miR-34a function (i.e., downstream targets). Importantly, our approach bypasses any liabilities associated with blunt miR-34a mimic delivery. These issues include off-target effects and delivery vehicle-mediated toxicities that previously hindered efforts to translate miR-34a replacement into clinical reality. The proposed experiments will elucidate and rank the significance of miR-34a-related programs, an inherently novel direction with the potential to yield new therapeutic opportunities.`;
